name: Commands
main: net.twasiplugin.commands.CommandsPlugin
author: Twasi Team
description: Lets you create your own commands. Please use '!help commands' to get an introduction.
helpText: Use !add to add a commands, !edit to edit one or !delete to remove one.
version: "1.0.0"

messageHandler: true

commands:
  - add
  - edit
  - del
  - commands
  - setaccess

permissions:
  - commands.mod.add
  - commands.mod.edit
  - commands.mod.delete
  - commands.mod.set-access
  - commands.broadcaster.set-access
  - commands.user.list

api: |
  type Commands {
    commands: TwasiCommandPageable,
    update(id: String, name: String, content: String, cooldown: Int, accessLevel: String, uses: Int): TwasiCommand,
    single(id: String): TwasiCommand,
    delete(id: String): TwasiCommand,
    create(name: String, content: String, cooldown: Int, accessLevel: String): TwasiCommand,
    accessLevels: [TwasiCommandAccessLevel]
  }

  pageable type TwasiCommand {
    id: String,
    name: String,
    content: String,
    uses: Int,
    cooldown: Int,
    accessLevel: TwasiCommandAccessLevel
  }

  type TwasiCommandAccessLevel {
    name: String,
    value: Int
  }