name: Commands
main: net.twasiplugin.commands.CommandsPlugin
author: Twasi Team
description: Lets you create your own commands. Please use '!help commands' to get an introduction.
helpText: Use !add to add a command, !edit to edit one or !delete to remove one.
version: 1.0

messageHandler: true

commands:
  - add
  - edit
  - delete
  - commands

permissions:
  - commands.mod.add
  - commands.mod.edit
  - commands.mod.delete
  - commands.user.list

api: |
  type Commands {
    commands: [TwasiCommand],
    update(id: String, name: String, content: String): TwasiCommand,
    single(id: String): TwasiCommand,
    delete(id: String): TwasiCommand,
    create(name: String, content: String): TwasiCommand
  }

  type TwasiCommand {
    id: String,
    name: String,
    content: String,
    uses: Number
  }