name: commands
main: net.twasiplugin.commands.CommandsPlugin
author: Twasi Team
description: Lets you create your own commands. Please use '!help commands' to get an introduction.
helpText: Use !add to add a command, !edit to edit one or !delete to remove one.
version: 1.0

# We need to check for a custom command
messageHandler: true

# Call our plugins Command Handler if !hello is executed.
# You have to register all your plugins commands here
# if you want to get all messages, please use onMessage.
# Please only use lowercase.
commands:
  - add
  - edit
  - delete
  - commands

permissions:
  - commands.mod.add
  - commands.mod.edit
  - commands.mod.delete
  - commands.user.list